title: SAN MARCOS ES DE TODOS
url: "https://sanmarcosesdetodos.github.io/docu/"
baseurl: "/docu"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
#footer_url: "https://github.com/ankitsultana"
footer_text: "UNMSM en el ‚ù§"

sass:
    style: compressed
    sass_dir: _sass

#nav:
 #- name: "About"
 #  link: "/researcher/"
 #- name: "Resume"
 #  link: "resume.pdf"
 #- name: "Contact"
 #  link: "contact"
